from . import hr_applicant
from . import hr_attendance
from . import hr_contract
from . import hr_employee
from . import hr_expense
from . import hr_expense_approve_duplicate
from . import hr_expense_refuse_wizard
from . import hr_expense_sheet
from . import hr_expense_split
from . import hr_expense_split_wizard
from . import hr_job
from . import hr_payroll_declaration_mixin
from . import hr_recruitment_stage
